declare module '*.module.css';
declare module '*.module.scss';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.scss';
declare module '*.module.scss';
declare module '*.js';
declare module 'react-base64-to-pdf';
